CREATE TABLE IF NOT EXISTS ccpayment_transactions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    reference_id VARCHAR(64) NOT NULL,
    user_id INT NOT NULL,
    payment_id INT NULL,
    purpose VARCHAR(32) NOT NULL DEFAULT 'connects',
    connects_amount INT NULL,
    amount_usd DECIMAL(12, 2) NOT NULL,
    chain VARCHAR(32) NOT NULL DEFAULT 'TRX',
    coin_symbol VARCHAR(16) NOT NULL DEFAULT 'USDT',
    deposit_address VARCHAR(255) NULL,
    memo VARCHAR(255) NULL,
    status ENUM('pending', 'awaiting_confirm', 'completed', 'failed') NOT NULL DEFAULT 'pending',
    ccpayment_record_id VARCHAR(255) NULL,
    deposited_amount DECIMAL(18, 8) NULL,
    deposited_coin VARCHAR(16) NULL,
    deposited_usd DECIMAL(12, 2) NULL,
    tx_id VARCHAR(255) NULL,
    webhook_payload JSON NULL,
    api_request JSON NULL,
    api_response JSON NULL,
    user_confirmed_at TIMESTAMP NULL,
    completed_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ccpayment_reference (reference_id),
    KEY idx_ccpayment_user (user_id),
    KEY idx_ccpayment_status (status),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
